// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUyfuYPc_S9BwebCK5AIJKiAXZy0p_UA',
    appId: '1:54872790776:web:ddbc525c414b25632c4d0d',
    messagingSenderId: '54872790776',
    projectId: 'myspotify02-23e5f',
    authDomain: 'myspotify02-23e5f.firebaseapp.com',
    storageBucket: 'myspotify02-23e5f.appspot.com',
    measurementId: 'G-MTGDTSELX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGR4ENqjCuiSoGf5YoCtEaCVKtXtJYwI',
    appId: '1:54872790776:android:557c0da3d21aaec92c4d0d',
    messagingSenderId: '54872790776',
    projectId: 'myspotify02-23e5f',
    storageBucket: 'myspotify02-23e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3fyB-CID_M9Xqea-6qxB67Xdi6rZpxnY',
    appId: '1:54872790776:ios:98eb3048dfb865972c4d0d',
    messagingSenderId: '54872790776',
    projectId: 'myspotify02-23e5f',
    storageBucket: 'myspotify02-23e5f.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3fyB-CID_M9Xqea-6qxB67Xdi6rZpxnY',
    appId: '1:54872790776:ios:98eb3048dfb865972c4d0d',
    messagingSenderId: '54872790776',
    projectId: 'myspotify02-23e5f',
    storageBucket: 'myspotify02-23e5f.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlUyfuYPc_S9BwebCK5AIJKiAXZy0p_UA',
    appId: '1:54872790776:web:d1036d1d1816cd6c2c4d0d',
    messagingSenderId: '54872790776',
    projectId: 'myspotify02-23e5f',
    authDomain: 'myspotify02-23e5f.firebaseapp.com',
    storageBucket: 'myspotify02-23e5f.appspot.com',
    measurementId: 'G-12KYW0BKYD',
  );
}
